controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute

api_graphql_entrypoint:
    path: /graphql
    controller: api_platform.graphql.action.entrypoint
